Remoção de verificações de acessibilidade
marado/RNID pull request #88
Opened 2021-10-30 22:14 UTC by hugopeixoto

O observatório português de acessibilidade web já faz esta
monitorização. Para evitar duplicar esforços, vamos deixar de registar
estes incumprimentos.

2021-10-30 22:14 UTC, hugopeixoto commented
Fixes #68

2021-10-31 15:12 UTC, hugopeixoto commented
Sempre que a github action correr, este PR vai ficar com conflitos por ambos mudarem o README.

Fiz rebase hoje, mas caso não seja já merged e para evitar andar a fazer isso todos os dias, peço-te, @marado, que me avises quando fores olhar para isto para fazer um rebase nesse dia.

2021-10-31 16:09 UTC, marado requested changes
O incumprimento do IMT não é só de acessibilidade, o resto será de manter…

2021-10-31 16:15 UTC, hugopeixoto commented
> O incumprimento do IMT não é só de acessibilidade, o resto será de manter…

O resto parece-me já ter sido corrigido também. Pelo que percebi, era um certificado expirado no URL https://www.imt-ip.pt/sites/IMTT/Portugues/Formularios/Documents/Mod9IMT.pdf

2021-10-31 16:36 UTC, marado commented
O curl continua a falhar:

```
$ curl https://www.imt-ip.pt/sites/IMTT/Portugues/Formularios/Documents/Mod9IMT.pdf
-o /dev/null; echo $?
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed
 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
60
```

Em https://whatsmychaincert.com/?www.imt-ip.pt confirma-se que há
problemas de configuração.


On Sun, Oct 31, 2021 at 4:16 PM Hugo Peixoto ***@***.***> wrote:
>
> O incumprimento do IMT não é só de acessibilidade, o resto será de manter…
>
> O resto parece-me já ter sido corrigido também. Pelo que percebi, era um certificado expirado no URL https://www.imt-ip.pt/sites/IMTT/Portugues/Formularios/Documents/Mod9IMT.pdf
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-10-31 16:47 UTC, hugopeixoto commented
Alright, já vou voltar a adicionar então. Tinha percebido mal o problema.

2021-10-31 17:54 UTC, hugopeixoto commented
Corrigido, podes confirmar?

2021-10-31 18:03 UTC, marado approved these changes

2021-10-31 18:03 UTC, merged